# SQL Server

development:
  adapter: mysql
  host: localhost
  database: chessonrails_development
  username: chessonrails
  password: ch3550nrails

test: &TEST
  #use either sqllite section or mysql 
  #adapter: sqlite3
  #database: ":memory:"
  #verbosity: quiet
  
  adapter: mysql
  host: localhost
  database: chessonrails_test
  username: chessonrails
  password: ch3550nrails

cucumber:
  <<: *TEST